### PR TITLE
Disabled stack protection before cleaning

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards https://github.com/giantswarm/giantswarm/issues/3740

### CODE REVIEW

**Review by tuommaki — APPROVED** [review]
LGTM given it's tested.

**Review by rossf7 — APPROVED** [review]
LGTM

**Review by fgimenez — COMMENTED** [review]
Nice, thanks for taking care. Why did Gopkg.lock change? According to the changes it should be the same AIUI.

**Comment by pipo02mix** [comment]
@fgimenez fixed, I think I run `dep ensure` by mistake

**Review by fgimenez — APPROVED** [review]
Cool thx!

**Pull request merged**
